# References: 
# https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml
# https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

image: maven:3.6.3-jdk-11-openj9

# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "--show-version \
                   --batch-mode \
                   -Duser.timezone=Asia/Jakarta \
                   -Dhttps.protocols=TLSv1.2 \
                   -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository \
                   -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN \
                   -Dorg.slf4j.simpleLogger.showDateTime=true \
                   -Djava.awt.headless=true"

cache:
 paths:
   - .m2/repository/

build:
  stage: build
  script: mvn $MAVEN_CLI_OPTS spotless:check test-compile -U
  allow_failure: false

test-h2:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS verify -U
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

test-postgresql:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS verify -Dspring.profiles.active=test-postgresql -U
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

test-mysql:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS verify -Dspring.profiles.active=test-mysql -U
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
